// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFjZvsb1TOHXXLxrKRDL-XRiSdl3R2iY',
    appId: '1:102410511518:web:a33fbe81caa8ae4ee5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    authDomain: 'tuni-transport-20eaf.firebaseapp.com',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    measurementId: 'G-PPSEHLZS6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPYKsXUlCsddWjBABpPyZJyqdXvAYM4_k',
    appId: '1:102410511518:android:13dd0186b21ba41de5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHONfz8DvfW_PjnSQyijIc_R0ebJxlfw',
    appId: '1:102410511518:ios:46b27f52fa74440ae5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    iosClientId: '102410511518-qqquua0t20jsrojmrrb5td12h8otnotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMHONfz8DvfW_PjnSQyijIc_R0ebJxlfw',
    appId: '1:102410511518:ios:46b27f52fa74440ae5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    iosClientId: '102410511518-qqquua0t20jsrojmrrb5td12h8otnotp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIFjZvsb1TOHXXLxrKRDL-XRiSdl3R2iY',
    appId: '1:102410511518:web:394eebb9d965bf31e5078f',
    messagingSenderId: '102410511518',
    projectId: 'tuni-transport-20eaf',
    authDomain: 'tuni-transport-20eaf.firebaseapp.com',
    storageBucket: 'tuni-transport-20eaf.firebasestorage.app',
    measurementId: 'G-XPSTNX7HLX',
  );
}
